<?php

namespace TelemonitoreoBundle\Repository;

/**
 * EquipoMedicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoMedicoRepository extends \Doctrine\ORM\EntityRepository
{
}
