<?php

namespace TelemonitoreoBundle\Repository;

/**
 * HistoricosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricosRepository extends \Doctrine\ORM\EntityRepository
{
}
