<?php

namespace TelemonitoreoBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * HistoricosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricosRepository extends EntityRepository
{
}
