<?php

namespace TelemonitoreoBundle\Repository;

/**
 * HistoriaClinicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriaClinicaRepository extends \Doctrine\ORM\EntityRepository
{
}
