<?php

namespace TelemonitoreoBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * HistoriaClinicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriaClinicaRepository extends EntityRepository
{
}
