<?php

namespace TelemonitoreoBundle\Repository;

/**
 * PatronPatologicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatronPatologicoRepository extends \Doctrine\ORM\EntityRepository
{
}
