<?php

namespace TelemonitoreoBundle\Repository;

/**
 * VariableHasPacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariableHasPacienteRepository extends \Doctrine\ORM\EntityRepository
{
}
